version: '3.5'

services:
  postgres:
    container_name: teste-postgres
    image: postgres
    environment:
      POSTGRES_USER:"postgres"
      POSTGRES_PASSWORD: "hitest123"
    volumes:
       - /home/hitest/Dev/PostgreSQL:/var/lib/postgresql/data 
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@test.com.br"
      PGADMIN_DEFAULT_PASSWORD: "hit123"
    ports:
      - "15432:80"
    networks:
      - postgres-network
    restart: unless-stopped

networks:
  postgres-network:
    driver: bridge

volumes:
    postgres:
